# Generated by Django 4.2.26 on 2026-01-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='brand',
        ),
    ]
