# Generated by Django 4.2.26 on 2026-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_facebook_url_brand_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
