# Generated by Django 4.2.26 on 2026-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
